### PR TITLE
Proposed rewrite of experimental-philology umbrella group

### PR DESCRIPTION
**Pull request by JonathanReeve**
This rewrites some of the language of the umbrella group and adds the constituent projects. 

I propose the umbrella group be renamed 'experimental-textualities', but that's just the first thing that came to mind, so feel free to change it. For me, philology doesn't quite make sense, since to me it sounds like more of an analytic discipline than a creative one. That is, the creation of minimal editions and the reimagining of editorial workflows sounds less like a philological project, and one that belongs more to the realm of the text/book/edition, whatever that might be called. But if there's a rationale for philology that I'm missing, feel free to revert it.  

Also included here is a fix to the `_layouts/people.html` layout, without which my copy of the site wouldn't compile. I'll submit that as a separate PR, which will automatically remove it from this one once it's merged.

### CODE REVIEW

**Comment by denten** [comment]
I am fine with any name as long as you guys talk it out as a group. @susannalles do you have a strong feeling one way or another? @elotroalex ? i do think that we should not overuse the word experimental so perhaps suggest something else? also, this branch has conflicts please resolve and refile. really excited to see this coming together. thank you for being the first to try this consolidation thing.

**Comment by JonathanReeve** [comment]
Nevermind, it looks like the new research strain was removed in 079e4d88e56310343708e8e3650cbe3f7f8b532c, so these changes don't make sense anymore. So I'll close this PR. But it might be useful as a very preliminary sketch of an umbrella group description. 

I think I agree that maybe the umbrella group shouldn't be a research strain (three strains is such a nice number), but I'm also not quite sure where it would go in the hierarchy. Maybe we could talk about it next Friday.

**Comment by elotroalex** [comment]
work session on friday sounds good to me. i'll throw in the word 'cluster'
for you guys to think about before we meet

**Comment by denten** [comment]
I think the idea was to just fold it under the some post with different sections representing each project. I would hate to lose the rewrites---the whole point is to get people to formulate common research goals and iterate over text. I suggest adding the edits to http://xpmethod.plaintext.in/public-discourse/experimental-philology.html and adding all your names there for now.

**Comment by susannalles** [comment]
Yes, exactly, neither I am sure where to feet these three projects. @elotroalex 's Ed project is under Minimal Computing, @JonathanReeve 's and mine is under Public discourse. In either way, GitLit and Vitae has also a component of Minimal... And about the name, well, philology also implies text editing, so not excessively bad. Remember that next Friday I won't be here!

**Comment by susannalles** [comment]
Yes, I agree with you Dennis.

**Comment by denten** [comment]
Yeah cluster or lab or something like that. The question is how to represent these smaller collectives in the site's data structure. Right now we are using categories for the three broad "research strains". These are useful to differentiate the lab as a whole. It would be useful for @susannalles job talk to get this done well before friday. 

I suggest just consolidating under her page now. We can revert / do something different later.

**Comment by elotroalex** [comment]
probably wise to not be too rigid about the received data structure or the
received strains. none of these things are written in stone. though we
should be cognizant of the amount of work to shift. i can imagine for
example rotating the 3 major strains each year. that will allow us to say
things like in the 2016 volume we worked on x, y and z large themes. since
the existing strains are top-level, highly-abstracted,
pay-attention-to-us-funders-and-traditional-academics, we could migrate
them to a mission statement, and out of the freaking data structure. that
said, that means re-working that structure

**Comment by JonathanReeve** [comment]
I put the description edits in #133 in case they're of use.

**Comment by susannalles** [comment]
Great!

**Comment by denten** [comment]
@elotroalex yes, i like the idea of changing focus but again think about *iteration* rather than rewrite---the idea is to shift and grow organically. we are not currently benefiting from iteration. 99% of commits are new files, with almost zero editing. think of practices that encourage collab: editing, reusing, improving, etc.

**Comment by elotroalex** [comment]
agreed. let's focus on the iteration first, before shifting wholesale
structures.

**Comment by gwijthoff** [comment]
Sorry I'm just coming to this conversation now.  Can we reflect this ongoing iteration in the description of strains themselves on the research page?  No need to shift the structures in this case, or add a third level to our ontology.  We'd just encourage community participation in editing the strains as we see them emerging, as if it were a collective overview of the directions the group is going.

**Comment by elotroalex** [comment]
I like that idea

**Pull request closed without merging**
