### PR TITLE
Add Wandering Rocks project.

### PR DESCRIPTION
**Pull request by muziejus**

### CODE REVIEW

**Comment by denten** [comment]
I think you forgot to add the .png to /images

**Comment by muziejus** [comment]
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	2017-01-07-mapping-fabula-and-sjuzet.md
	../../public/images/fabulaandsjuzet.png

nothing added to commit but untracked files present (use "git add" to track)
 moacir@opus  ~/Projects/xpmethod.github.io/_posts/projects   master  ga .
 moacir@opus  ~/Projects/xpmethod.github.io/_posts/projects   master ✚  gcm "Add Wandering Rocks project."
[master fb6f71e] Add Wandering Rocks project.
 1 file changed, 24 insertions(+)
 create mode 100644 _posts/projects/2017-01-07-mapping-fabula-and-sjuzet.md
```

How weird. It sees two files, but `git add .` doesn't add both.


fabulaandsjuzet

**Comment by denten** [comment]
Use `git add -A` to add all untracked files. The way you have it just means "all files in this directory."

**Comment by muziejus** [comment]
duh of course. You do a new project and seemingly basic operations swim past by you because of infamiliarity w/ the project as a whole. I always keep my shell at the root level of a project, but for this dug deep…

**Comment by denten** [comment]
If you don't mind, I'll put this under literary-modeling-and-visualization-lab.

**Pull request merged**
