### PR TITLE
Issue #230

### PR DESCRIPTION
**Pull request by nyutka**

### CODE REVIEW

**Comment by denten** [comment]
Anne, can I see a preview of this change?

**Comment by nyutka** [comment]
Sure, here it is

https://nyutka.github.io/xpmethodd.github.io/

**Comment by nyutka** [comment]
@denten  Is everything ok?

**Comment by denten** [comment]
This looks great. Lets get "view all" to be in a different font from the section name. We also need to clearly label "selected project." To go with the spirit of our original design, I suggest a text corner, in the following format:

 ▼ selected projects | view all  ⯈

**Pull request merged**
