### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by caseymhenry**
As per my conversation with Dennis Tenen, and discussions with the Group when I attended roughly two weeks ago, I am uploading my Finnegans Wake project, which translates annotations to the text musically. In this way, the project holds certain overlaps and resonances with Emily Furhman's project on "Sirens." I can ideally see the project categorized under Theory-Method.

### CODE REVIEW

**Comment by denten** [comment]
Casey, see the files in the _posts/projects directory for a template of how to add projects to our portfolio. Let me know if you have any questions. Best,
Dennis

**Comment by caseymhenry** [comment]
Dennis,

Sorry for the delayed response. I've looked at the files in
_posts/projects, yet am still a bit unclear on how I would target my pull
request to the most appropriate area on the group's GitHub site. Is there a
simple series of steps I can find somewhere? I believe my last pull request
was just to the general group's GitHub--do I simply need to direct the pull
request to the "posts/projects" directory? Any info would be greatly
appreciated. Thank you.

Best,
Casey

**Comment by denten** [comment]
Heya, Casey. First take a look at our projects page and see where you would like to fit (Most likely in literary-modeling-and-visualization-lab). Then look at one of the files in _posts/projects/ directory to see how to properly format the .yaml front matter. The file needs to be titled properly (today's date then the name). The category tag on top determines where it shows up. Let me know if you have any questions. Also feel free to stop by our lab tomorrow and I can help you in person.

**Comment by caseymhenry** [comment]
Dennis,

Thanks for the information--much obliged. Tomorrow is a little crunched for
me, but i'd happily attend next Friday and take you up on your generous
offer to help out, if you'll be around then? Thanks again.

Best,
Casey

**Comment by denten** [comment]
Sounds good. Just email a day or so in advance. Meanwhile, take a look at the files. Best,

DT

**Comment by caseymhenry** [comment]
Hi Dennis,

Hope you've been well. I realized I dropped the ball temporarily, before
the break, but I've just re-submitted the pull request for my project,
modeled on the preexisting projects in _posts/projects directory. I hope
this looks good, and viable, from your end. Let me know if there's anything
else I can do from my end. Thanks again! & I hope to drop by an XP methods
meeting soon.

Best,
Casey

**Pull request closed without merging**
