### PR TITLE
switch to tachyons #203

### PR DESCRIPTION
**Pull request by nyutka**

### CODE REVIEW

**Comment by denten** [comment]
Anne, I had to revert. That PR broke the theme pretty badly. Ideally, we would want exactly the same look on every page. Try to compare side by side on your local build.

**Comment by nyutka** [comment]
hm. strange.. haven't you done any screenshots?

**Comment by denten** [comment]
I'll take screenshots tonight

**Comment by JonathanReeve** [comment]
Just to throw out an idea, if you're testing out big structural changes to the site, it might be a good idea to do them on a new branch, and then build the test branch using something like [Netlify](https://www.netlify.com/) (which is more or less a GitHub Pages clone). That way everyone can see what it looks like, without having to affect the public-facing site.

**Comment by nyutka** [comment]
@JonathanReeve  Good idea thanks. 

So I set up github pages, for my forked repo. Here is the url for it. You can see all my changes here, before merging it

https://nyutka.github.io/xpmethodd.github.io/

**Comment by nyutka** [comment]
@denten  also if you want exact the same look, I will set up the font sizes and families for each element.

**Comment by denten** [comment]
Yes, the same exact look. You can see that to avoid mutating the underlying CSS I've added a global.css on my site (https://github.com/denten/denten.github.io/blob/master/public/global.css), which sets default font styles.

I would go page by page and migrate the logic from old css to new inline tachyons. Anne, let's try to get in touch briefly again by Skype. Let me know what works for you.

**Comment by nyutka** [comment]
Hey @denten  let me know when you will be available to discuss this issue

**Pull request merged**
